Adding Public wireshark code

diff --git a/tools/commit-msg b/tools/commit-msg
--- a/tools/commit-msg
+++ b/tools/commit-msg
@@ -1,26 +1,16 @@
 #!/bin/sh
-# From Gerrit Code Review 2.9-rc1-172-gd621a9e
+# From Gerrit Code Review 2.12.7
 #
-# Part of Gerrit Code Review (http://code.google.com/p/gerrit/)
+# Part of Gerrit Code Review (https://www.gerritcodereview.com/)
 #
 # Copyright (C) 2009 The Android Open Source Project
 #
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-# http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+# SPDX-License-Identifier: Apache-2.0
 #
 
 unset GREP_OPTIONS
 
-CHANGE_ID_AFTER="Bug|Issue"
+CHANGE_ID_AFTER="Bug|Issue|Test"
 MSG="$1"
 
 # Check for, and add if missing, a unique Change-Id
@@ -39,7 +29,19 @@ add_ChangeId() {
 		return
 	fi
 
+	# Do not add Change-Id to temp commits
+	if echo "$clean_message" | head -1 | grep -q '^\(fixup\|squash\)!'
+	then
+		return
+	fi
+
 	if test "false" = "`git config --bool --get gerrit.createChangeId`"
+	then
+		return
+	fi
+
+	# Do not add Change-Id on packaging branches
+	if git branch | grep -q '^\* \(debian\|ubuntu\)/'
 	then
 		return
 	fi
@@ -57,6 +59,10 @@ add_ChangeId() {
 		# Solaris AWK is just too broken
 		AWK=/usr/xpg4/bin/awk
 	fi
+
+	# Get core.commentChar from git config or use default symbol
+	commentChar=`git config --get core.commentChar`
+	commentChar=${commentChar:-#}
 
 	# How this works:
 	# - parse the commit message as (textLine+ blankLine*)*
@@ -76,8 +82,8 @@ add_ChangeId() {
 		blankLines = 0
 	}
 
-	# Skip lines starting with "#" without any spaces before it.
-	/^#/ { next }
+	# Skip lines starting with commentChar without any spaces before it.
+	/^'"$commentChar"'/ { next }
 
 	# Skip the line starting with the diff command and everything after it,
 	# up to the end of the file, assuming it is only patch data.
@@ -177,5 +183,14 @@ _gen_ChangeId() {
 	git hash-object -t commit --stdin
 }
 
+reject_long_message() {
+	read -r firstline < $MSG
+	if [ ${#firstline} -gt 80 ]
+	then
+		echo "\n\nERROR: First line in the commit message must not exceed 80 characters\n\n"
+		exit 1
+	fi
+}
 
 add_ChangeId
+reject_long_message
diff --git a/tools/pre-commit b/tools/pre-commit
--- a/tools/pre-commit
+++ b/tools/pre-commit
@@ -3,6 +3,9 @@
 #
 # For git user: copy tools/pre-commit to .git/hooks/ folder and make it
 # executable. To bypass it for a single commit, use the --no-verify argument.
+# Using --no-verify will then fail during git review because of a missing
+# ChangeID. Fix that by running git review -i. Do not use -i during normal
+# operation.
 #
 # Alternatively, invoke it directly with the commit ID. Example for checking the
 # last commit:
@@ -10,7 +13,7 @@
 #   tools/pre-commit HEAD~
 #
 # Relative paths are also supported. For instance, if you are in epan/, then you
-# could invoke `../tools/pre-commit HEAD` to check for changes to staged files.
+# could invoke  `../tools/pre-commit HEAD` to check for changes to staged files.
 #
 # From
 # http://mark-story.com/posts/view/using-git-commit-hooks-to-prevent-stupid-mistakes
@@ -19,7 +22,7 @@
 # If the commit identifier is not given, use HEAD instead.
 COMMIT_ID="${1:-HEAD}"
 
-UNAME=`uname -a`
+UNAME=$( uname -a )
 
 case "$UNAME" in
     *\ Msys)
@@ -37,30 +40,32 @@ hook_script=${GIT_DIR:-.git}/hooks/pre-commit
 
 # Always start in the root directory of the source tree, this allows for
 # invocations via relative paths (such as ../tools/pre-commit):
-cd "$(git rev-parse --show-toplevel)"
+if ! cd "$(git rev-parse --show-toplevel)" ; then
+    echo "Can't change to the top-level source directory."
+    exit 1
+fi
 
 # Check for newer (actually, different) versions of the pre-commit script
 # (but only if invoked as hook, i.e. the commit ID is not given as argument).
-if [ -z "$1" ] && ! cmp -s "$hook_script" tools/pre-commit; then
-    echo "Pre-commit hook script is outdated, please update!"
+if [ -z "$1" ] && [ -f "$hook_script" ]; then
+    if ! cmp -s "$hook_script" tools/pre-commit; then
+        echo "Pre-commit hook script is outdated, please update! (cp tools/pre-commit ${hook_script})"
+    fi
 fi
 
 exit_status=0
 
-COMMIT_FILES=`git diff-index --cached --name-status ${COMMIT_ID} | grep -v "^D" | cut -f2 | grep "\.[ch]$"`
+COMMIT_FILES=$( git diff-index --cached --name-status "${COMMIT_ID}" | grep -v "^D" | cut -f2 | grep "\\.[ch]$" )
+DIAMETER_FILES=$( git diff-index --cached --name-status "${COMMIT_ID}" | grep -v "^D" | cut -f2 | grep diameter/ )
 
 # Path to filter script in the tools directory
 filter_script=${PWD}/tools/pre-commit-ignore.py
 filter_conf=${PWD}/tools/pre-commit-ignore.conf
 
-if [ ! -e "$filter_script" ]; then
-    echo "File '$filter_script' does not exist. Aborting."
-    exit 1
-fi
-
-CHECK_FILES=`echo "$COMMIT_FILES" | "$PYBIN" "$filter_script" "$filter_conf"`
-if [ $? -ne 0 ]; then
-    exit 1
+if [ -f "$filter_script" ] && [ -f "$filter_conf" ]; then
+    CHECK_FILES=$( echo "$COMMIT_FILES" | "$PYBIN" "$filter_script" "$filter_conf" ) || exit
+else
+    CHECK_FILES="$COMMIT_FILES"
 fi
 
 # On windows python will output \r\n line endings - we don't want that.
@@ -72,26 +77,31 @@ fi
 #
 # The Single UNIX Specification says that tr supports \r; most if not
 # all modern UN*Xes should support it.
-CHECK_FILES=`echo "$CHECK_FILES" | tr -d '\r'`
+CHECK_FILES=$( echo "$CHECK_FILES" | tr -d '\r' )
 
 for FILE in $CHECK_FILES; do
 
     #Check if checkhf is good
-    ./tools/checkhf.pl $FILE            || exit_status=1
+    ./tools/checkhf.pl "$FILE"            || exit_status=1
 
     #Check if checkAPIs is good
-    ./tools/checkAPIs.pl -p $FILE       || exit_status=1
+    ./tools/checkAPIs.pl -p "$FILE"       || exit_status=1
 
     #Check if fix-encoding-args is good
-    ./tools/fix-encoding-args.pl $FILE  || exit_status=1
+    ./tools/fix-encoding-args.pl "$FILE"  || exit_status=1
 
     #Check if checkfiltername is good
-    ./tools/checkfiltername.pl $FILE    || exit_status=1
+    ./tools/checkfiltername.pl "$FILE"    || exit_status=1
+
+    # If there are whitespace errors, print the offending file names and fail. (from git pre-commit.sample)
+    git diff-index --check --cached "${COMMIT_ID}" "$FILE" || exit_status=1
 
 done
 
-# If there are whitespace errors, print the offending file names and fail. (from git pre-commit.sample)
-git diff-index --check --cached ${COMMIT_ID}    || exit_status=1
+if [ "x$DIAMETER_FILES" != x ]
+then
+    ./tools/validate-diameter-xml.sh > /dev/null || exit_status=1
+fi
 
 exit $exit_status
 
